# Generated by Django 2.2.16 on 2020-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='权限名称'),
        ),
    ]
