# Generated by Django 2.2.16 on 2020-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='当前uid1')),
                ('uid2', models.IntegerField(verbose_name='好友uid2')),
            ],
            options={
                'unique_together': {('uid1', 'uid2')},
            },
        ),
    ]
